modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/someElseIsHere/sonicboom/issues"
license = "GPL-3.0"

[[mods]]
modId = "sonicboom"
version = "${version}"
displayName = "Sonic Boom"
authors = "thePlaceholder"
description = '''
a useless client side mod
'''
logoFile = "../assets/sonicboom/icon.png"

[[dependencies.sonicboom]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sonicboom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"